apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: {{team}}
  name: tag-stillingstittel
  namespace: arbeidsgiver
spec:
  accessPolicy:
    outbound:
      external:
        - host: {{pam_search_api_host}}
      rules: []
    inbound:
      rules:
        - application: istio-ingressgateway
          namespace: istio-system
  image: {{version}}
  port: {{port}}
  team: {{team}}
  liveness:
    path: {{liveness_path}}
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: {{readiness_path}}
    initialDelay: 10
    timeout: 1
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingresses:
    - "https://stillingstittel.gc.nav.no"
  logformat: accesslog
  logtransform: dns_loglevel
  env:
    - name: APP_VERSION
      value: {{version}}
    - name: PORT
      value: {{port}}

