ingress:
  - https://tiltak-stillingstitler.intern.dev.nav.no
env:
  JANZZ_URL: http://pam-janzz.teampam
external-host:
  - arbeidsplassen.intern.dev.nav.no
extra-inbound-apps:
  - tiltaksgjennomforing-labs
