apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-stillingstitler
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  team: arbeidsgiver
  port: 4000
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/is_alive
    initialDelay: 10
  readiness:
    path: /internal/is_ready
    initialDelay: 10
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingresses:
    {{#each ingress}}
    - {{this}}
    {{/each}}
  env:
    {{#each env}}
     - name: "{{@key}}"
       value: "{{this}}"
    {{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: pam-janzz
          namespace: teampam
      external:
        {{#each external-host}}
          - host: "{{this}}"
        {{/each}}
    inbound:
      rules:
        - application: tiltaksgjennomforing
        - application: tiltaksgjennomforing-intern
        {{#each extra-inbound-apps}}
        - application: {{this}}
        {{/each}}